/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2023

class Day1 {
    fun getLines(): List<String> {
        return this.javaClass.classLoader.getResource("day1input.txt").readText().split("\n");
    }
}

fun main() {
    var sum = 0
    try {
        Day1().getLines().forEach { line ->
            val firstNumber = line.first { c -> c.isDigit() }.toString().toInt()
            val lastNumber = line.last { c -> c.isDigit() }.toString().toInt()
            val combinedNumber = firstNumber * 10 + lastNumber
            sum += combinedNumber;
        }
    } catch (e: Exception) {
        println(e)
    }
    println(sum)
}
